/* OBŮRKA 5-7 4. 2024 */
export const PrihlaseniUcastnciAkce1 = [
  { name: "Martin Ďásek", paid: "680 Kč" },
  { name: "Šufeislová Emma", paid: "680 Kč" },
  { name: "Šufeislová Isabella ", paid: "680 Kč" },
  { name: "Březinová Michaela", paid: "680 Kč" },
  { name: "Jedličková Lucie", paid: "680 Kč" },
  { name: "Figarová Kateřina", paid: "680 Kč" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
];
