// Obůrka
export const PrihlaseniUcastnciAkce1 = [
  { name: "Březinová Míša", paid: "680 Kč" },
  { name: "Zlatá Valerie", paid: "680 Kč" },
  { name: "Šťastná Emma", paid: "680 Kč" },
  { name: "Figarová Kateřina", paid: "680 Kč" },
  { name: "Křenek Matěj", paid: "680 Kč" },
  { name: "Strašáková Karolína", paid: "680 Kč" },
  { name: "Šufeislová Emma", paid: "680 Kč" },
  { name: "Šufeislová Isabela", paid: "680 Kč" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" }
];
