export const PrihlaseniUcastnciTabor = [
  { name: "Rozsíval Adam", paid: "5000 Kč" },
  { name: "Goldová Karolína", paid: "5000 Kč" },
  { name: "Hendy Andrew", paid: "5000 Kč" },
  { name: "Bärová Lenka", paid: "5000 Kč - chybí přihláška" },
  { name: "Des Tomáš", paid: "2000 Kč" },
  { name: "Přibylová Dominika", paid: "5000 Kč" },
  { name: "Přibylová Jasmína", paid: "5000 Kč" },
  { name: "Revai Miroslav", paid: "5000 Kč" },
  { name: "Revai Valentina", paid: "5000 Kč" },
  { name: "Revai Karolína", paid: "5000 Kč" },
  { name: "Popovych Veronika", paid: "5000 Kč" },
  { name: "Kovalčík Martin", paid: "5000 Kč" },
  { name: "Kovalčíková Gabriela", paid: "5000 Kč" },
  { name: "Macháčková Alžběta", paid: "5000 Kč" },
  { name: "Macháček Šimon", paid: "5000 Kč" },
  { name: "Nováček Šimon", paid: "5000 Kč" },
  { name: "Nováček Štěpán", paid: "5000 Kč" },
  { name: "Žilková Sofie", paid: "5000 Kč" },
  { name: "Pokorný Lukáš", paid: "5000 Kč" },
  { name: "Šormová Anita", paid: "5000 Kč" },
  { name: "Posádka Antonín", paid: "2000 Kč - chybí přihláška" },
  { name: "Phuong Thi Phamová Saiti", paid: "5000 Kč" },
  { name: "Kafka Matyáš", paid: "2000 Kč" },
  { name: "Kafka Robin", paid: "2000 Kč" },
  { name: "Kafková Eliška", paid: "2000 Kč" },
  { name: "Pelc Vít", paid: "5000 Kč" },
  { name: "Zahradníková Ema", paid: "5000 Kč" },
  { name: "Mařa Antonín", paid: "5000 Kč" },
  { name: "Priadko Kira", paid: "5000 Kč" },
  { name: "Sušánková Petra", paid: "2500 Kč" },
];
