export const PrihlaseniUcastnciTabor = [
  { name: "Hendy Andrew", paid: "2500" },
  { name: "Nováček Šimon", paid: "2500" },
  { name: "Nováček Štěpán", paid: "2500" },
  { name: "Rousek Josef", paid: "2500" },
  { name: "Rousek Jan", paid: "2500" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
];
