export const PrihlaseniUcastnciTabor = [
  { name: "Hendy Andrew", paid: "6290 Kč" },
  { name: "Rousek Jan", paid: "6290 Kč" },
  { name: "Rousek Josef", paid: "6290 Kč" },
  { name: "Nováček Štěpán", paid: "6290 Kč" },
  { name: "Nováček Šimon", paid: "6290 Kč" },
  { name: "Buchtová Markéta", paid: "6290 Kč" },
  { name: "Des Ondřej", paid: "6290 Kč" },
  { name: "Ďásek Martin", paid: "6290 Kč" },
  { name: "Jurečková Zuzka", paid: "6290 Kč" },
  { name: "Pospíšilová Lucie", paid: "6290 Kč" },
  { name: "Zvěřina Štěpán", paid: "2500 Kč" },
  { name: "Zahradníková Ema", paid: "6290 Kč" },
  { name: "Bahulová Lucie", paid: "6290 Kč" },
  { name: "Goldová Karolína", paid: "6290 Kč" },
  { name: "Kovalčík Martin", paid: "6290 Kč" },
  { name: "Kovalčíková Gabriela", paid: "6290 Kč" },
  { name: "Bär Lukáš", paid: "6290 Kč" },
  { name: "Bär Vojtěch", paid: "6290 Kč" },
  { name: "Bärová Lenka", paid: "6290 Kč" },
  { name: "Macháčková Alžběta", paid: "6290 Kč" },
  { name: "Sušánková Petra", paid: "6290 Kč" },
  { name: "Kafka Robin", paid: "2500 Kč" },
  { name: "Kafka Matyáš", paid: "2500 Kč" },
  { name: "Křenek Matěj", paid: "2500 Kč" },
  { name: "Matyáš Adam", paid: "2500 Kč" },
  { name: "Popovych Veronika", paid: "6290 Kč" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
];
