/* Vagon */
export const PrihlaseniUcastnciAkce2 = [
  { name: "Šufeislová Emma", paid: "-" },
  { name: "Šufeislová Isabella", paid: "-" },
  { name: "Přibylová Dominika", paid: "600 Kč" },
  { name: "Přibylová Jasmína", paid: "600 Kč" },
  { name: "Posádka Antonín", paid: "600 Kč" },
  { name: "Jurečková Zuzka", paid: "600 Kč" },
  { name: "Kolářová Andrea", paid: "600 Kč" },
  { name: "Kafka Matyáš", paid: "-" },
  { name: "Kafka Robin", paid: "-" },
  { name: "Kafková Eliška", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" }, {/*
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" } */}
];
