/* Výlet */
export const PrihlaseniUcastnciAkce2 = [
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  {/*{ name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" },
  { name: "", paid: "-" } */}
];
