export const PrihlaseniUcastnciAkce3 = [

  // 2. TURNUS
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
];
