export const PrihlaseniUcastnciAkce3 = [

  // 2. TURNUS
  { name: "Šufeislová Isabella", paid: "1000 Kč" },
  { name: "Šufeislová Emma", paid: "1000 Kč" },
  { name: "Březinová Michaela", paid: "1000 Kč" },
  { name: "Figarová Kateřina", paid: "1000 Kč" },
  { name: "Jurečková Zuzka", paid: "" },
  { name: "Krčmářová Klára", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
  { name: "", paid: "" },
];
